export const projects = [
  {
    title: 'Personal Portfolio',
    description: "My personal portfolio website developed with the help of React.js and styled components.",
    image: '/images/portfolio.png',
    tags: ['Styled-components', 'React', 'Next'],
    source: 'https://google.com',
    visit: 'https://github.com/kunalvirmani98/portfolio',
	  // visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Adopt-me',
    description: "This is a pet adoption website frontend-only built with react.js. It lists the various pets that are up for adoption. ",
    image: '/images/pets.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://github.com/kunalvirmani98/adopt-me',
	  // visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Quizzo',
    description: "Quizzo is a quiz application that tests your learning and increases your knowledge as you attempt more and more quizzes. It is built with react.js",
    image: '/images/quiz.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://github.com/kunalvirmani98/quizzo',
	// visit: 'https://google.com',
    id: 2,
  },
  {
    title: '2Chat',
    description: "2Chat is a chat application. It is currently under development. it is built with the help of react js and socket.io",
    image: '/images/2chat.png',
    tags: ['JavaScript', 'React', 'Socket.io'],
    source: 'https://google.com',
    // visit: 'https://github.com/kunalvirmani98/2chat',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Joined Thapar University as a COE student', },
  { year: 2020, text: 'Graduated with a CGPA 8/10', },
  { year: 2020, text: 'Worked as an intern in Antares Tech, Noida', },
  { year: 2020, text: 'Joined Ericsson India Pvt Ltd as a software developer', },
  { year: 2022, text: 'Joined Antares Tech Noida as an associate designer in Feb 2022', },
];
